[IV-24-25] Objetivo 5
MarioRgzLpz/ArbitrageBets pull request #35
Opened 2024-12-19 11:01 UTC by MarioRgzLpz

* [x] ¿Se han establecido criterios previos de elección de la imagen base, así
como los criterios de búsqueda que han conducido a las imágenes que se están
considerando?
* [x] ¿Se ha tenido en cuenta que la imagen es para testear, y que por tanto
tiene una función específica, tal como testear cómo va nuestra aplicación en la
última versión publicada del lenguage?
* [x] ¿Se ha tenido en cuenta que la versión de la imagen base sea la última?
* [x] ¿Se han tenido en cuenta criterios reales para la elección, y no criterios
irrelevantes como cuanto tiempo se tarda en construirla? (Se va a construir una
vez, se va a usar cientos o miles de veces)
* [x] ¿Se han seguido las buenas prácticas en las órdenes que construyen
   la imagen? ¿Especialmente las relativas a usuarios no privilegiados y demás?
* [x] ¿La imagen incluye sólo y exclusivamente la infraestructura
   necesaria para pasar los tests? Por ejemplo, si se ha elegido la imagen
   "oficial" (lo que hay que hacer sólo en casos muy justificados) ¿se ha
   comprobado que lo que se instale sea sólo y exclusivamente lo necesario para
   nuestro proyecto?
* [x] ¿Se han documentado y enlazado los commits a las imágenes que se
   han testeado?
* [x] ¿Está establecido correctamente como `WORKDIR` el que se va a usar en los
   tests que se van a lanzar?
* [x] ¿Se usa algún directorio adecuado para copiar contenidos del repositorio
en vez del directorio de trabajo?
* [x] ¿Se han establecido claramente los criterios de búsqueda y de aceptación de
   la imagen base?
* [x] ¿Tienes claro cuales son las condiciones en las que tiene que actualizarse
la imagen en DockerHub y has configurado el workflow de acuerdo con ello? En
particular, ¿sabes qué condiciones tienen que darse para que se actualice y qué
condiciones *no* deben darse?
* [x] Si se usan GitHub actions para su publicación, ¿se han considerado
cuidadosamene los criterios (ramas, paths) para que se lancen?
* [x] ¿Se ha comprobado que el ENTRYPOINT del contenedor no escriba nada en el
directorio que monta, ya que no tiene derecho de escritura?
* [x] ¿Se ha abierto un shell en el contenedor una vez construida la imagen y
comprobado que los ficheros que se necesitan están todos incluidos, y que no hay
ficheros que no se necesiten?

## Esta PR cierra el siguiente issue:
closes #30

2024-12-19 11:33 UTC, antoniorr02 reviewed
Buenas tardes, se me ha asignado a revisar tu PR, en general está bastante bien, pero te comento un par de detalles que debes de arreglar.

2024-12-19 11:33 UTC, antoniorr02 commented on Dockerfile
> +RUN adduser --disabled-login --uid 1001 test && chown -R test:test /app/test
No es correcto dar el uid 1001, ya que debe de funcionar con cualquier uid.

2024-12-19 11:33 UTC, antoniorr02 commented on docs/imagen-docker.md
> +- Que tenga Rust instalado por defecto.
Esto realmente que ventaja te da, ¿es muy complicado instalar rust?

2024-12-19 12:03 UTC, JLombar reviewed
Esta práctica es un poco complicada si no has usado mucho docker. Revisa bien lo has hecho y  después mira que te hemos comentado el compañero y yo para que entiendas bien lo que te decimos.

2024-12-19 12:03 UTC, JLombar commented on Dockerfile
> +COPY data/ ./data/
Todo esto si te das cuenta se convierte en duplicados

2024-12-19 12:03 UTC, JLombar commented on Dockerfile
> +RUN cargo build --release
Esto te instala dependencias? Piensa por qué podría ser innecesario al montar el volumen. Te recomiendo entrar a la imagen de forma interactiva con:
> docker run -u 1001 -it -v $(pwd):/app/test {nombre_alumno}/{nombre_repo}:latest /bin/bash

Siempre que tengas un shell como bash (o sh, si no puedes intentar instalarlos)

2024-12-19 12:03 UTC, JLombar commented on docs/imagen-docker.md
> +Comparando los tamaños y viendo lo que yo necesito en mi proyecto, he decidido usar rust:slim, que me permite realizar lo que yo quiero con el menor tamaño posible, evitando instalar dependencias adi
Has comprobado que la imagen no tenga funcionalidades extras innecesarias?

2024-12-19 18:59 UTC, MarioRgzLpz commented on docs/imagen-docker.md
> +Comparando los tamaños y viendo lo que yo necesito en mi proyecto, he decidido usar rust:slim, que me permite realizar lo que yo quiero con el menor tamaño posible, evitando instalar dependencias adi
Segun la página oficial de Rust en DockerHub contiene solo los paquetes y dependencias mínimos para poder usar rust.

2024-12-19 19:10 UTC, MarioRgzLpz commented on docs/imagen-docker.md
> +- Que tenga Rust instalado por defecto.
Instalar Rust de manera explícita va a añadir bastante complejidad al Dockerfile (necesita muchas dependencias) y a la construcción de la imagen, algo a tener bastante en cuenta, ya que Rust es bastante pesado por defecto y al tener que añadir cargo-make y cargo-nextest la construcción, de por si, es bastante lenta. Además encontramos imagenes oficiales con SO mínimos como Alpine o Debian-slim y las dependencias mínimas para poder ejecutar Rust por lo que veo innecesario el intentar replicar algo que ya esta hecho.

2024-12-19 19:38 UTC, MarioRgzLpz commented on docs/imagen-docker.md
> +- Preferiblemente oficial o de un publisher verificado.
Resuelto aquí -> [885e5c7](https://github.com/MarioRgzLpz/ArbitrageBets/pull/35/commits/885e5c7c8475d111a94f1611309127d18db1364b)

2024-12-19 19:38 UTC, MarioRgzLpz commented on Dockerfile
> +RUN adduser --disabled-login --uid 1001 test && chown -R test:test /app/test
Resuelto aquí -> [d1dd35c](https://github.com/MarioRgzLpz/ArbitrageBets/pull/35/commits/d1dd35cfef55a5f2363b81760a98cc36ea37f220)

2024-12-19 19:39 UTC, MarioRgzLpz commented on Dockerfile
> +COPY data/ ./data/
Resuelto aquí -> [d1dd35c](https://github.com/MarioRgzLpz/ArbitrageBets/pull/35/commits/d1dd35cfef55a5f2363b81760a98cc36ea37f220)

2024-12-19 19:39 UTC, MarioRgzLpz commented on Dockerfile
> +RUN cargo build --release
Sin ambas herramientas no puedo ejecutar la orden cargo make test, aunque he eliminado la orden cargo build como puedes ver aquí -> [d1dd35c](https://github.com/MarioRgzLpz/ArbitrageBets/pull/35/commits/d1dd35cfef55a5f2363b81760a98cc36ea37f220)

2024-12-19 19:39 UTC, MarioRgzLpz commented on README.md
> +docker build -t mariorgzlpz/arbitragebets . && docker run -t -v `pwd`:/app/test mariorgzlpz/arbitragebets
Resuelto aquí -> [cab874c](https://github.com/MarioRgzLpz/ArbitrageBets/pull/35/commits/cab874c305381ff61ad69c2b70e0f4af1e6bae3c)

2024-12-19 19:40 UTC, MarioRgzLpz commented on .github/workflows/ci.yml
> +      - 'data/**'
Cierto, lo he resuelto aquí -> [222654f](https://github.com/MarioRgzLpz/ArbitrageBets/pull/35/commits/222654f9581122bd0923beee1ca9eef500dac488)

2024-12-19 19:40 UTC, MarioRgzLpz commented on Dockerfile
> +RUN adduser --disabled-login --uid 1001 test && chown -R test:test /app/test
Resuelto aquí -> [d1dd35c](https://github.com/MarioRgzLpz/ArbitrageBets/pull/35/commits/d1dd35cfef55a5f2363b81760a98cc36ea37f220)

2024-12-19 19:43 UTC, MarioRgzLpz commented
Muchas gracias a @antoniorr02 y @JLombar por vuestros comentarios, me han aclarado varias cosas. Ya he realizado los cambios sugeridos. Si os parecen correctos o tenéis alguna objeción decidmelo por favor. Quedo a la espera de que me aprobéis.

2024-12-20 07:36 UTC, JLombar commented
Creo que tu dockerfile no es correcto como te dije ayer en clase, pero si tu crees que sí pídele revisión a Juan y que lo revise él correctamente

2024-12-20 08:43 UTC, MarioRgzLpz commented
@JLombar He modificado el Dockerfle quitando el ultimo RUN y poniendo todos en el mismo. ¿Que sería lo que no es correcto?

2024-12-20 10:54 UTC, JLombar reviewed
Creo que la línea que te marco abajo no es necesaria. Si te hace falta seguramente algo está mal, pero como digo, puede ser que yo esté equivocado por que no sé como funcionan tus herramientas. Pídele revisión a Juan que te sabrá decir mejor que yo

2024-12-20 10:54 UTC, JLombar commented on Dockerfile
> +COPY Cargo.toml Makefile.toml /app/
.

2024-12-20 16:23 UTC, MarioRgzLpz commented on Dockerfile
> +COPY Cargo.toml Makefile.toml /app/
Efectivamente parece que no hace falta. Resuelto aquí -> [5ff02a0](https://github.com/MarioRgzLpz/ArbitrageBets/pull/35/commits/5ff02a065ce00ba23fa0c36e19535b54aa1e8268)

2024-12-20 16:23 UTC, MarioRgzLpz commented
@JJ Buenas después de unas cuantas correcciones creo que esta listo para revisión.

2024-12-22 18:03 UTC, JJ commented
¿Lo vas a dejar así o vas a añadir nuevas imágenes?

2024-12-22 19:06 UTC, MarioRgzLpz commented
@JJ finalmente he implementado la construcción en dos fases como bien muestro [aquí](https://github.com/MarioRgzLpz/ArbitrageBets/pull/35/commits/83332efc90da3877ab8e063b092d2073ac5eadaa). Gracias por la atención e insistencia para que aprenda, siento que he entendido bastante mejor Docker y como optimizarlo. Creo que con esto queda listo el objetivo.

2024-12-23 08:43 UTC, JJ requested changes
Si quieres darle una vueltecita al tema de la construcción en dos fases (y al enlace simbólico), creo que aprenderás un poquito más.

2024-12-23 08:43 UTC, JJ commented on Dockerfile
> +RUN ln -s /app/test/src /app/src
Esta es una ñapa buena, pero no veo que incumpla ninguna buena práctica. Siendo un link simbólico no importa que no exista en el momento de creación; en el momento que se ejecute, sin embargo, va a ser una especie de redirección que va a permitir "meter" el directorio interno "dentro" del contenedor. Supongo que cargo make va buscando en directorios superiores los fuentes. En todo caso, yo probaría a ver si eso es realmente necesario que me da la impresión de que es el típico "Funciona, pero por una razón diferente por la que tú crees que funcioan"

2024-12-23 08:43 UTC, JJ commented on Dockerfile
> +FROM rust:slim
Si usas otra vez la misma base, ¿qué ganas con ello? Simplemente vas a eliminar algunas cosas que se hayan instalado por `cargo install` que no necesites, los 200 megas célebres. En las segundas fases se suelen usar algunos llamados "scratch", por ejemplo (que no tienen ni shell)

2024-12-23 09:35 UTC, MarioRgzLpz commented on Dockerfile
> +RUN ln -s /app/test/src /app/src
Efectivamente, eso que tenía no sirve para nada. Creo que se debe a que antes copiaba directamente los ficheros al contenedor, algo que no es necesario al montar el volumen como bien me indicó @JLombar, y si que era necesario para que cargo encontrase los fuentes. Lo arreglo aquí -> [6806e1c](https://github.com/MarioRgzLpz/ArbitrageBets/pull/35/commits/6806e1c06a154ce179e69cfe5f81342642b271a3)

2024-12-23 09:45 UTC, MarioRgzLpz commented
@JJ revisión.

2024-12-23 10:39 UTC, JJ commented on Dockerfile
> +FROM rust:slim
Contestar no es resolver. Deberías haber intentado resolver los problemas; empezar desde cero no tiene por qué ser una buena solución, ni lo es nunca.
Dejo sin resolver para que expliques correctamente el proceso de elección de una imagen "solo para los binarios". Si se pregunta, es que hay algo que no se entiende.

2024-12-23 10:43 UTC, JJ requested changes
No había visto las otras conversaciones no resueltas. Por favor, resuélvelo todo.

2024-12-23 10:43 UTC, JJ commented on Dockerfile
> +COPY --from=build /usr/local/cargo/bin/cargo-make /usr/local/bin/cargo-make
Si usas el mismo nombre para el fichero ¿el nombre del directorio sería suficiente?. Y si estás haciendo dos copias al mismo directorio, ¿se podrían hacer en una sola?

2024-12-23 10:43 UTC, JJ commented on docs/imagen-docker.md
> +- Que tenga Rust instalado por defecto.
Igual que te digo más arriba, no se puede cerrar un comentario simplemente contestándolo.

2024-12-23 10:43 UTC, JJ commented on docs/imagen-docker.md
> +Comparando los tamaños y viendo lo que yo necesito en mi proyecto, he decidido usar rust:slim, que me permite realizar lo que yo quiero con el menor tamaño posible, evitando instalar dependencias adi
Por favor, resuelve correctamente las conversaciones.

2024-12-23 19:20 UTC, MarioRgzLpz commented on Dockerfile
> +COPY --from=build /usr/local/cargo/bin/cargo-make /usr/local/bin/cargo-make
La primera pregunta no la entiendo, sobre la segunda, pues si que se podría. De todas formas he actualizado el dockerfile y ahora empleo la construcción en dos fases pero solo copio el binario de los tests. Resuelto aquí -> [10d78df](https://github.com/MarioRgzLpz/ArbitrageBets/pull/35/commits/10d78dfab0d9aa0124b5ceb19dd1099e44c54eae)

2024-12-23 19:25 UTC, JJ commented on Dockerfile
> +COPY --from=build /usr/local/cargo/bin/cargo-make /usr/local/bin/cargo-make
Cuando pones como segundo argumento el path completo incluyendo el nombre del fichero, ¿necesitas poner este o con el nombre del directorio es suficiente?

2024-12-23 19:26 UTC, MarioRgzLpz commented on Dockerfile
> +FROM rust:slim
Resuelto aquí -> [10d78df](https://github.com/MarioRgzLpz/ArbitrageBets/pull/35/commits/10d78dfab0d9aa0124b5ceb19dd1099e44c54eae)

2024-12-23 19:26 UTC, MarioRgzLpz commented on docs/imagen-docker.md
> +Comparando los tamaños y viendo lo que yo necesito en mi proyecto, he decidido usar rust:slim, que me permite realizar lo que yo quiero con el menor tamaño posible, evitando instalar dependencias adi
Resuelto aquí -> [fc75e94](https://github.com/MarioRgzLpz/ArbitrageBets/pull/35/commits/fc75e9452a866bed7d3ffbc429001b2a3ced4d55)

2024-12-23 19:27 UTC, MarioRgzLpz commented on docs/imagen-docker.md
> +- Que tenga Rust instalado por defecto.
He completa la explicación aquí -> [fc75e94](https://github.com/MarioRgzLpz/ArbitrageBets/pull/35/commits/fc75e9452a866bed7d3ffbc429001b2a3ced4d55)

2024-12-23 19:28 UTC, MarioRgzLpz commented
@JJ He resuelto los comentarios, además de modificar el dockerfile para lograr la ejecución en dos fases usando solo el binario de los tests. Queda listo para revisión.

2024-12-23 19:46 UTC, JJ requested changes
En algún momento en la creación de código se te ha olvidado crear un issue, o has planteado el problema equivocado en el mismo olvidándote del fin principal. Por favor, da un pasito atrás, mira lo que has hecho, y piensa a ver qué momento ha sido ese.

2024-12-23 19:46 UTC, JJ commented on Dockerfile
> +ENTRYPOINT [ "/app/arbitrage_bets" ]
El ENTRYPOINT tiene que ser forzosamente `cargo make test`. No sé lo que hace esto, pero no tiene pinta de que ejecute los tests. Para eso se hace el objetivo 3 y el 4 antes que este, para crear la infraestructura para que se pueda hacer.

2024-12-23 19:46 UTC, JJ commented on Dockerfile
> +    && chown -R test:test /app/
¿Has creado un grupo `test` ?

2024-12-23 19:46 UTC, JJ commented on Dockerfile
> +RUN find /app/ -type f -executable -name 'arbitrage_bets-*' ! -name '*.d' -exec mv {} /app/arbitrage_bets \;
No sé lo que haces aquí, pero me da impresión de que no haces nada de lo que se pide en este objetivo, que es ejecutar los tests. No hay ninguna orden en la que efectivamente ejecutes los tests sobre los fuentes.

2024-12-23 19:46 UTC, JJ commented on Dockerfile
> +    && cargo make test
¿En qué momento se ha dicho que hay que pasar los tests en la construcción de la imagen?

2024-12-25 09:49 UTC, MarioRgzLpz commented on Dockerfile
> +    && cargo make test
Es la única forma de hacer que en la primera fase se pueda generar el binario de los tests. Como he eliminado esta forma de ejecutar los tests queda resuelto aquí -> [8ff72b1](https://github.com/MarioRgzLpz/ArbitrageBets/pull/35/commits/8ff72b1342650f11055f9deda32543b040ae04f3)

2024-12-25 09:49 UTC, MarioRgzLpz commented on Dockerfile
> +RUN find /app/ -type f -executable -name 'arbitrage_bets-*' ! -name '*.d' -exec mv {} /app/arbitrage_bets \;
Al usar cargo make test se generan los binarios de los tests siendo el nombre `arbitrage_bets-hash` y como el hash es distinto para cada vez, lo renombro para poder ejecutar dicho binario usando siempre el mismo comando en el entrypoint. Queda resuelto aquí ->[8ff72b1](https://github.com/MarioRgzLpz/ArbitrageBets/pull/35/commits/8ff72b1342650f11055f9deda32543b040ae04f3)

2024-12-25 09:49 UTC, MarioRgzLpz commented on Dockerfile
> +    && chown -R test:test /app/
El comando adduser crea por defecto un grupo primario con el mismo nombre del usuario y al que se asigna el usuario, por lo que no sería necesario crearlo explicitamente. Pero si es verdad que ni si quiera es necesario hacer al usuario test propietario de /app para que funcione, por lo que directamente lo elimino -> [8ff72b1](https://github.com/MarioRgzLpz/ArbitrageBets/pull/35/commits/8ff72b1342650f11055f9deda32543b040ae04f3)

2024-12-25 09:49 UTC, MarioRgzLpz commented on Dockerfile
> +ENTRYPOINT [ "/app/arbitrage_bets" ]
Ejecuta el binario creado al hacer cargo make test en la primera fase. Es la única forma en la que puedo reducir el tamaño de la imagen, ya que si no forzosamente debo tener tanto los binarios de cargo make como los de cargo nextest y esto implica usar la imagen de rust en ambas fases para poder usar los binarios en la segunda, ya que una instalación manual de rust sobre debian me acaba dando los mismos resultados que usar la imagen con rust ya instalado. Procedo entonces a dejar el Dockerfile para que funcione el comando cargo make test -> [8ff72b1](https://github.com/MarioRgzLpz/ArbitrageBets/pull/35/commits/8ff72b1342650f11055f9deda32543b040ae04f3)

2024-12-25 09:50 UTC, MarioRgzLpz commented
@JJ gracias por lo sugerido. Queda listo para revisión.

2024-12-30 11:24 UTC, JJ approved these changes
:+1:

2025-01-03 23:07 UTC, merged